export const client = {
  name: "K.H. Landscaping and Sons",
  tagline: "Professional Landscaper in Wallsend — Quality You Can Trust",
  description: "Professional landscaper services in Wallsend and surrounding areas. Trusted local experts with 49 Google reviews.",
  category: "Landscaper",
  yearEstablished: "2015",
  phone: "",
  email: "",
  website: "",
  address: "",
  city: "Wallsend",
  county: "",
  postcode: "",
  basedIn: "Wallsend",
  founderName: "John",
  founderSurname: "",
  founderRole: "Director",
  facebook: "",
  instagram: "",
  linkedin: "",
  twitter: "",
  googleRating: "4.6",
  reviewCount: "49",
  services: [
    { title: "Garden Design", description: "Bespoke garden designs tailored to your lifestyle and space.", icon: "tree" },
    { title: "Landscaping", description: "Complete hard and soft landscaping to transform your outdoor area.", icon: "shovel" },
    { title: "Paving & Patios", description: "Beautiful paving solutions using premium natural stone and porcelain.", icon: "wall" },
    { title: "Planting Schemes", description: "Year-round colour and interest with expertly curated planting plans.", icon: "flower" },
  ],
  cinematic: {
    frameCount: 181, frameDir: "/frames/", framePrefix: "frame_", frameExtension: ".jpg",
    framePadding: 4, scrollLength: "500vh", mobileFrameCount: 181, mobileFrameDir: "/frames-mobile/",
    scrubSpeed: 0.5, heroStillImage: "/images/hero-still.jpg", heroStillImageMobile: "/images/hero-still-mobile.jpg",
  },
  beforeAfter: { beforeImage: "/images/before.jpg", afterImage: "/images/after.jpg", beforeLabel: "Current Garden", afterLabel: "Our Vision" },
  transformations: [
    { before: "/images/before.jpg", after: "/images/after.jpg", label: "Complete Garden Renovation" },
    { before: "/images/patio-before.jpg", after: "/images/patio-after.jpg", label: "Patio & Fencing" },
    { before: "/images/front-before.jpg", after: "/images/front-after.jpg", label: "Front Garden" },
    { before: "/images/lawn-before.jpg", after: "/images/lawn-after.jpg", label: "Lawn Restoration" },
    { before: "/images/fence-before.jpg", after: "/images/fence-after.jpg", label: "New Fencing" },
    { before: "/images/deck-before.jpg", after: "/images/deck-after.jpg", label: "Decking & Furniture" },
    { before: "/images/path-before.jpg", after: "/images/path-after.jpg", label: "Garden Path" },
    { before: "/images/border-before.jpg", after: "/images/border-after.jpg", label: "Planting Borders" },
    { before: "/images/drive-before.jpg", after: "/images/drive-after.jpg", label: "Driveway" },
  ] as { before: string; after: string; label: string }[],
  reviews: [
    { name: "Shannon Byers", rating: 5, text: "Absolutely over the moon with our garden transformation, big thank you to Shaun, Rod and Steve for their hard-work and how fantastic our garden looks. Highly recommend this company for any landscaping/garden design", date: "2 weeks ago" },
    { name: "Moira Heppell", rating: 5, text: "Excellent professional job transforming our garden. Tidy reliable team who work hard. I would have no hesitation in recommending Shaun, Rod and Steve. Thank you so much.", date: "3 weeks ago" },
    { name: "Rianna Margione", rating: 5, text: "I can’t recommend these guys more. From the quote to completion, there was great communication and contact. My garden wasn’t a massive high value job but I felt like they took as much care and commitment as a big job. My paved jungle of a garden was totally transformed and they went above and beyond and kept me involved the whole way through, asking me about any details that I might want/change. Also kept everything really tidy and were super efficient and knowledgeable! Thank you ☺️", date: "a month ago" },
    { name: "James Simpson", rating: 5, text: "We highly recommend this company for any landscaping works. They transformed our garden to exactly what we wanted. Shaun and his teams attention to detail, hard work and attitude is to be commended.", date: "5 months ago" },
    { name: "Richard Davies", rating: 5, text: "I would highly recommend this company to any one who needs work on their garden. We needed a old decking removed and replaced by a patio. This was no mean task as old decking some 6 meters by 4.5 metres. We were given a very competitive price and a time scale of 3 days to complete including removal of all old decking. The work was done exactly as was quoted and way above our expectations. I would recommend this company without any reservations. The guys doing this job were a delight and a credit to British workmen", date: "10 months ago" },
    { name: "David", rating: 5, text: "Already recommend these guys to family and friends.  A team with a wealth of experience and an eye for detail that take pride in what they do, that is shown in the care, thought and considered way they work. So happy with their hard work and result. Cheers guys...", date: "11 months ago" },
  ] as { name: string; rating: number; text: string; date: string; badge?: string }[],
  seo: {
    title: "K.H. Landscaping and Sons | Professional Landscaper in Wallsend",
    description: "Professional landscaper in Wallsend. 4.6 stars on Google with 49 reviews. Quality workmanship guaranteed.",
  },
};
